/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Sustella AI:",
  "tagline": "Multi-Agent System",
  "favicon": "/img/sustella-logo3.svg",
  "url": "https://chaos-mesh.org",
  "baseUrl": "/",
  "organizationName": "chaos-mesh",
  "projectName": "chaos-mesh.github.io",
  "onBrokenLinks": "warn",
  "trailingSlash": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "zh"
    ],
    "localeConfigs": {
      "en": {
        "label": "English",
        "direction": "ltr"
      },
      "zh": {
        "label": "简体中文",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "presets": [
    [
      "classic",
      {
        "gtag": {
          "trackingID": "G-T31S4LR9LL"
        },
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/chaos-mesh/website/edit/master/",
          "editLocalizedFiles": true
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/chaos-mesh/website/edit/master/",
          "editLocalizedFiles": true
        },
        "theme": {
          "customCss": "./src/styles/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "image": "/img/sustella-logo3.svg",
    "algolia": {
      "appId": "3BY0S3HQX6",
      "apiKey": "99bb3af44d57f0e8f6d7e019d7e2c2d7",
      "indexName": "chaos-mesh",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "Sustella AI",
      "logo": {
        "alt": "Chaos Mesh",
        "src": "img/logos/sustella-logo1.png",
        "srcDark": "img/logos/sustella-logo1.png"
      },
      "items": [
        {
          "to": "docs",
          "label": "Documentation",
          "position": "left"
        },
        {
          "to": "blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "https://community.cncf.io/chaos-mesh-community/",
          "label": "Community Group",
          "position": "left"
        },
        {
          "type": "docsVersionDropdown",
          "dropdownItemsAfter": [
            {
              "type": "html",
              "value": "<hr style=\"margin: .5em 0;\" />"
            },
            {
              "to": "/versions",
              "label": "All Versions"
            },
            {
              "to": "/supported-releases",
              "label": "Supported Releases"
            }
          ],
          "position": "right",
          "dropdownItemsBefore": []
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/chaos-mesh/chaos-mesh",
          "className": "header-github-link",
          "aria-label": "GitHub",
          "position": "right"
        }
      ]
    },
    "footer": {
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Quick Start",
              "to": "docs/quick-start"
            },
            {
              "label": "Run a Chaos Experiment",
              "to": "docs/run-a-chaos-experiment"
            },
            {
              "label": "Developer Guide Overview",
              "to": "docs/developer-guide-overview"
            },
            {
              "label": "FAQs",
              "to": "docs/faqs"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Blog",
              "to": "blog"
            },
            {
              "label": "CNCF Community Group",
              "href": "https://community.cncf.io/chaos-mesh-community/"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/chaos-mesh/chaos-mesh"
            },
            {
              "label": "Slack (#project-chaos-mesh)",
              "href": "https://slack.cncf.io/"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/chaos_mesh"
            }
          ]
        },
        {
          "title": "Acknowledgements",
          "items": [
            {
              "html": "\n              <ul>\n              <li>\n              <p style=\"font-size: 0.875rem;\">Thanks to netlify's Open Source Plan.</p>\n              <a href=\"https://www.netlify.com\" target=\"_blank\"><img src=\"https://www.netlify.com/v3/img/components/netlify-color-bg.svg\" alt=\"Deploys by Netlify\" /></a>\n              </li>\n              <li>\n              <p>Thanks for the <a href=\"https://storyset.com/technology\">Technology illustrations by Storyset</a>.</p>\n              </li>\n              </ul>"
            }
          ]
        }
      ],
      "copyright": "\n        <p style=\"font-weight: 500;\">Copyright © Chaos Mesh Authors 2024 | Documentation Distributed under CC-BY-4.0</p>\n        © 2024 The Linux Foundation. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our <a href=\"https://www.linuxfoundation.org/trademark-usage/\"> Trademark Usage</a> page.\n      ",
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          },
          {
            "types": [
              "function",
              "keyword"
            ],
            "style": {
              "color": "#f25c7c"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "plugins": [
    "./docusaurus-tailwind-v3",
    [
      "@gracefullight/docusaurus-plugin-microsoft-clarity",
      {
        "projectId": "lggqck9srz"
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
